.TH AMCLEANUP 8
.SH NAME
amcleanup \- runs the Amanda cleanup process after a failure
.SH SYNOPSIS
.B amcleanup
.I config 

.SH DESCRIPTION
.ad
.B Amcleanup
generates the 
.I Amanda Mail Report 
and updates the Amanda databases after a system failure on the master
host.  This cleanup process is normally done automatically as part of
the
.B amdump
program, but if
.B amdump
cannot complete for some reason (usually because of a host crash),
.B amcleanup
must be run some time later.
See the
.IR amanda(8)
man page for more details about Amanda.

.SH EXAMPLES
.TP
% amcleanup csd
Runs the Amanda cleanup process by hand during the day after
noticing a failure.

.PP
.nf
if [ -s /opt/amanda/adm/DailySet1/amanda.log ]
then
	${exec_prefix}/libexec/amcleanup csd
fi
.fi
.RS .5i
Putting the above in /etc/rc.local runs the Amanda
cleanup process when needed as part of the reboot, eliminating the need
to run it by hand.
.RE

.SH AUTHOR
James da Silva <jds@cs.umd.edu>
.br
University of Maryland, College Park

.SH "SEE ALSO"
amanda(8), amdump(8).
