.\"
.de EX
.if t .ft C
.nf
..
.de EE
.fi
.if t .ft
..
.TH AMRESTORE 8
.SH NAME
amrestore \- extract files from an Amanda tape
.SH SYNOPSIS
.B amrestore
[
.B \-r
|
.B \-c
]
[
.B \-p
]
[
.B \-h
]
.I tapedevice
[
.I hostname
[
.I diskname
[
.I datestamp
[
.I hostname
[
.I diskname
[
.I datestamp
\&...
]]]]]]
.SH DESCRIPTION
.B Amrestore
extracts files from the tape mounted on
.I tapedevice
that match
.IR hostname ,
.I diskname
and
.I datestamp
patterns given on the command line.
The tape must be in a format written by the
.B amdump
or
.B amflush
program.
.LP
If
.I diskname
is not specified, all backups on the tape for the previous
.I hostname
are candidates.
If
.I datestamp
is not specified, all backups on the tape for the previous
.I hostname
and
.I diskname
are candidates.
If no
.IR hostname ,
.I diskname
or
.I datestamp
are specified, every backup on the tape is a candidate.
.LP
.IR Hostname ,
.I diskname
and
.I datestamp
are regular expressions that may match more than one backup.
For example, if
.I diskname
is "rz[23]a", it would match disks
.B rz2a
and
.BR rz3a .
.IR Hostname ,
.I diskname
or
.I datestamp
may be an empty string ("") to match every host, disk or date
(this is just an abbreviation for ".*").
.LP
.I Datestamp
is useful if you have multiple
.B amflush
runs on the tape.
.PP
Unless
.B -p
is used,
candidate backup files are extracted to files
in the current directory named:
.LP
.RS
.I hostname.diskname.datestamp.dumplevel
.RE
.SH OPTIONS
.TP
.B -p
Pipe output.
The first matching backup file is sent to standard output,
which is normally a pipe to
.B restore
or
.BR tar ,
then
.B amrestore
quits.
It may be run again to continue selecting backups to process.
Make sure you specify the no-rewind
.I tapedevice
when doing this.
.IP
Note:
.B restore
may report "short read" errors when reading from a pipe.
Most versions of
.B restore
support a blocking factor option to let you set the read block size,
and you should set it to 2.
See the example below.
.TP
.B -c
Compress output.
.B Amrestore
normally writes output files in a format understood by
.B restore
or
.BR tar ,
even if the backups on the tape are compressed.
With the
.B -c
option,
.B amrestore
writes all files in compressed format,
even if the backups on the tape are not compressed.
Output file names will have a
.I .Z
extension.
This option is useful when the current directory disk is small.
.TP
.B -r
Raw output.
Backup files are output exactly as they are on the tape,
including the
.B amdump
file headers.
Output file names will have a
.I .RAW
extension.
This option is only useful for debugging and other strange circumstances.
.TP
.B -h
Header output.
The tape header block is output at the beginning of each file.
This is like
.B \-r
except
.B \-c
may also be used to compress the result.
.B Amrecover
uses the header to determine the restore program to use.
.SH EXAMPLES
The following does an interactive restore of disk
.I rz3g
from host
.IR seine ,
to restore particular files.
Note the use of the
.B b
option to
.BR restore ,
which causes it to read in units of two 512-byte blocks (1 Kbyte)
at a time.
This keeps it from complaining about short reads.
.LP
.RS
.EX
% amrestore -p /dev/nrmt9 seine rz3g | restore ivbf 2 -
.EE
.RE
.LP
The next example extracts all backup files for host
.IR seine .
This is the usual way to extract all data for a host after a disk crash.
.LP
.RS
.EX
% amrestore /dev/nrmt9 seine
.EE
.RE
.LP
If the backup datestamp in the above example is
.I 19910125
and
.I seine
has level 0 backups of disks
.I rz1a
and
.I rz1g
on the tape,
these files will be created in the current directory:
.LP
.RS
.EX
seine.rz1a.19910125.0
seine.rz1g.19910125.0
.EE
.RE
.SH AUTHOR
James da Silva <jds@cs.umd.edu>
.br
University of Maryland, College Park
.SH "SEE ALSO"
amanda(8),
amdump(8),
amflush(8),
restore(8)
