.TH AMTOC 1
.UC 4
.SH NAME
amtoc \- program to generate TOC (Table Of Content) for an amanda run
.SH SYNOPSIS
.B
.I amtoc
-c conf [-l label] [-h host] [-v] [-i] [-t] [-f]

.br
.SH DESCRIPTION
.I Amtoc
generate a TOC for an amanda run.
It's a perl script (If you don't have perl, install it first!).

.TP
.B \-c conf
select configuration

.TP
.B \-l label
label of the tape (default: last amanda run)

.TP
.B \-h host
only the specified host

.TP
.B \-v
verbose. Not realy a TOC, but a full dump of the database (may be restricted
with -l and -h options

.TP
.B \-i
information. Start TOC with a small help to restore files

.TP
.B \-t
use TAB to align record, use space by default. May be usefull to inlude
in a FrameMaker document.

.TP
.B \-f
file. create $conf/$label.TOC file. use STDOUT by default.

.SH TYPICAL USAGE
.I amdump
configuration;
.I amtoc
-c configuration -f

.SH See also
.I amanda
,
.I perl

.SH AUTHOR
Nicolas MAYENCOURT <nicolas@cui.unige.ch>
.br
University of Geneva/Switzerland

.SH BUGS
Amtoc only use the amanda-dbm-database (curinfo). So generating TOC for the
last run should be OK (confusing between date/tape label/... may happen).
Generating TOC for an older run is generaly only partial. This script work
with amanda 2.2.6 and 2.3.0.[0-3], it may or may not work with other release.

