#!/bin/sh
# This script is no longer (and in fact it was never) needed

# Please apply patches/autoreconf.patch to the autoreconf script in
# autoconf 2.12.

# Then, in order to rebuild the automake/autoconf files, you just have
# to run:

#     autoreconf -i --foreign [--force]
#

awk '/^#!\/bin\/sh/ { next } /^#.*/,/^#$/ { print }' <$0 |
sed 's/^# \?//'

echo "Now running autoreconf -i --foreign"
echo "(it will fail if you have not applied the patch yet)"
exec autoreconf -i --foreign
