/*
 * Amanda, The Advanced Maryland Automatic Network Disk Archiver
 * Copyright (c) 1991,1993 University of Maryland
 * All Rights Reserved.
 *
 * Permission to use, copy, modify, distribute, and sell this software and its
 * documentation for any purpose is hereby granted without fee, provided that
 * the above copyright notice appear in all copies and that both that
 * copyright notice and this permission notice appear in supporting
 * documentation, and that the name of U.M. not be used in advertising or
 * publicity pertaining to distribution of the software without specific,
 * written prior permission.  U.M. makes no representations about the
 * suitability of this software for any purpose.  It is provided "as is"
 * without express or implied warranty.
 *
 * U.M. DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL U.M.
 * BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
 * OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 * Author: James da Silva, Systems Design and Analysis Group
 *			   Computer Science Department
 *			   University of Maryland at College Park
 */
/*
 * $Id: genversion.c,v 1.10 1997/12/30 05:24:16 jrj Exp $
 *
 * dump the current Amanda version info
 */
#include "amanda.h"
#include "version.h"

int main P((void));

#define MARGIN 	70

#define newline() do {							\
    printf("  \"%s\\n\",\n", line);					\
    *line = '\0';							\
    linelen = 0;							\
} while (0)

#define prstr(string) do {						\
    int len = strlen(string);						\
    if(linelen+len >= MARGIN) { 					\
	newline(); 							\
	ap_snprintf(line, sizeof(line), "%*s", indent, "");		\
	linelen = indent;						\
    }									\
    line[sizeof(line)-1] = '\0';					\
    strncat(line, (string), sizeof(line)-strlen(line));			\
    linelen += len;							\
} while (0)

char *pname;

int main()
{
    char line[STR_SIZE], *str = NULL;
    int  linelen, indent;
    char major_str[NUM_STR_SIZE];
    char minor_str[NUM_STR_SIZE];
    char patch_str[NUM_STR_SIZE];
#ifdef KRB4_SECURITY
    char lifetime_str[NUM_STR_SIZE];
#endif

    pname = "genversion";

    printf("/* version.c - generated by genversion.c - DO NOT EDIT! */\n");
    printf("char *version_info[] = {\n");

    *line = '\0', linelen = 0, indent = 0;
    prstr("build:"); indent = linelen;

    ap_snprintf(major_str, sizeof(major_str), "%d", VERSION_MAJOR);
    ap_snprintf(minor_str, sizeof(minor_str), "%d", VERSION_MINOR);
    ap_snprintf(patch_str, sizeof(patch_str), "%d", VERSION_PATCH);
    str = newvstralloc(str,
		       " VERSION=\\\"Amanda-",
		       major_str, ".", minor_str, ".", patch_str,
		       VERSION_COMMENT,
		       NULL);
    prstr(str);
#ifdef BUILT_DATE
    str = newvstralloc(str, " BUILT_DATE=\\\"", BUILT_DATE, "\\\"", NULL);
    prstr(str);
#endif
#ifdef BUILT_MACH
    str = newvstralloc(str, " BUILT_MACH=\\\"", BUILT_MACH, "\\\"", NULL);
    prstr(str);
#endif
#ifdef CC
    str = newvstralloc(str, " CC=\\\"", CC, "\\\"", NULL);
    prstr(str);
#endif
    newline();
    prstr("paths:"); indent = linelen;
#ifdef DEV_PREFIX
    str = newvstralloc(str, " DEV_PREFIX=\\\"", DEV_PREFIX, "\\\"", NULL);
    prstr(str);
#endif
#ifdef RDEV_PREFIX
    str = newvstralloc(str, " RDEV_PREFIX=\\\"", RDEV_PREFIX, "\\\"", NULL);
    prstr(str);
#endif
#ifdef DUMP
    str = newvstralloc(str, " DUMP=\\\"", DUMP, "\\\"", NULL);
    prstr(str);
#endif
#ifdef RESTORE
    str = newvstralloc(str, " RESTORE=\\\"", RESTORE, "\\\"", NULL);
    prstr(str);
#endif
#ifdef XFSDUMP
    str = newvstralloc(str, " XFSDUMP=\\\"", XFSDUMP, "\\\"", NULL);
    prstr(str);
#endif
#ifdef XFSRESTORE
    str = newvstralloc(str, " XFSRESTORE=\\\"", XFSRESTORE, "\\\"", NULL);
    prstr(str);
#endif
#ifdef VXDUMP
    str = newvstralloc(str, " VXDUMP=\\\"", VXDUMP, "\\\"", NULL);
    prstr(str);
#endif
#ifdef VXRESTORE
    str = newvstralloc(str, " VXRESTORE=\\\"", VXRESTORE, "\\\"", NULL);
    prstr(str);
#endif
#ifdef SAMBA_CLIENT
    str = newvstralloc(str, " SAMBA_CLIENT=\\\"", SAMBA_CLIENT, "\\\"", NULL);
    prstr(str);
#endif
#ifdef GNUTAR
    str = newvstralloc(str, " GNUTAR=\\\"", GNUTAR, "\\\"", NULL);
    prstr(str);
#endif
#ifdef COMPRESS_PATH
    str = newvstralloc(str, " COMPRESS_PATH=\\\"", COMPRESS_PATH, "\\\"", NULL);
    prstr(str);
#endif
#ifdef UNCOMPRESS_PATH
    str = newvstralloc(str, " UNCOMPRESS_PATH=\\\"", UNCOMPRESS_PATH, "\\\"",
		       NULL);
    prstr(str);
#endif
    str = newvstralloc(str, " MAILER=\\\"", MAILER, "\\\"", NULL);
    prstr(str);
    str = newvstralloc(str, " bindir=\\\"", bindir, "\\\"", NULL);
    prstr(str);
    str = newvstralloc(str, " libexecdir=\\\"", libexecdir, "\\\"", NULL);
    prstr(str);
    str = newvstralloc(str, " CONFIG_DIR=\\\"", CONFIG_DIR, "\\\"", NULL);
    prstr(str);
    str = newvstralloc(str, " mandir=\\\"", mandir, "\\\"", NULL);
    prstr(str);
#ifdef GNUTAR_LISTED_INCREMENTAL_DIR
    str = newvstralloc(str,
		       " listed_incr_dir=\\\"",
		       GNUTAR_LISTED_INCREMENTAL_DIR,
		       "\\\"",
		       NULL);
    prstr(str);
#endif
    newline();

    prstr("defs: ");
    indent = linelen;
    str = newvstralloc(str, " DEFAULT_SERVER=\\\"", DEFAULT_SERVER, "\\\"",
		       NULL);
    prstr(str);
    str = newvstralloc(str, " DEFAULT_CONFIG=\\\"", DEFAULT_CONFIG, "\\\"",
		       NULL);
    prstr(str);
    str = newvstralloc(str,
		       " DEFAULT_TAPE_SERVER=\\\"",
		       DEFAULT_TAPE_SERVER,
		       "\\\"",
		       NULL);
    prstr(str);
    str = newvstralloc(str,
		       " DEFAULT_TAPE_DEVICE=\\\"",
		       DEFAULT_TAPE_DEVICE,
		       "\\\"",
		       NULL);
    prstr(str);

#ifdef AIX_BACKUP
    prstr(" AIX_BACKUP");
#endif
#ifdef AIX_TAPEIO
    prstr(" AIX_TAPEIO");
#endif
#ifdef BROKEN_VOID
    prstr(" BROKEN_VOID");
#endif
#ifdef DUMP_RETURNS_1
    prstr(" DUMP_RETURNS_1");
#endif
#ifdef HAVE_MMAP
    prstr(" HAVE_MMAP");
#endif
#ifndef HAVE_STRERROR
    prstr(" NEED_STRERROR");
#endif
#ifndef HAVE_STRSTR
    prstr(" NEED_STRSTR");
#endif
#ifdef HAVE_SYSVSHM
    prstr(" HAVE_SYSVSHM");
#endif
#ifdef USE_POSIX_FCNTL
    prstr(" LOCKING=POSIX_FCNTL");
#endif
#ifdef USE_FLOCK
    prstr(" LOCKING=FLOCK");
#endif
#ifdef USE_LOCKF
    prstr(" LOCKING=LOCKF");
#endif
#ifdef USE_LNLOCK
    prstr(" LOCKING=LNLOCK");
#endif
#if !defined(USE_POSIX_FCNTL) && !defined(USE_FLOCK) && !defined(USE_LOCK) && !defined(USE_LNLOCK)
    prstr(" LOCKING=**NONE**");
#endif
#ifdef OSF1_VDUMP
    prstr(" OSF1_VDUMP");
#endif
#ifdef STATFS_BSD
    prstr(" STATFS_BSD");
#endif
#ifdef STATFS_OSF1
    prstr(" STATFS_OSF1");
#endif
#ifdef STATFS_ULTRIX
    prstr(" STATFS_ULTRIX");
#endif
#ifdef SETPGRP_VOID
    prstr(" SETPGRP_VOID");
#endif
#ifdef ASSERTIONS
    prstr(" ASSERTIONS");
#endif
#ifdef DEBUG_CODE
    prstr(" DEBUG_CODE");
#endif
#ifdef DEBUG_FILE_WITH_PID
    prstr(" DEBUG_FILE_WITH_PID");
#endif
#ifdef BSD_SECURITY
    prstr(" BSD_SECURITY");
#endif
#ifdef USE_AMANDAHOSTS
    prstr(" USE_AMANDAHOSTS");
#endif
#ifdef USE_RUNDUMP
    prstr(" USE_RUNDUMP");
#endif
#ifdef KRB4_SECURITY
#define HOSTNAME_INSTANCE	"<hostname>"
    prstr(" KRB4_SECURITY");
    str = newvstralloc(str,
		       " SERVER_HOST_PRINCIPLE=\\\"",
		       SERVER_HOST_PRINCIPLE,
		       "\\\"",
		       NULL);
    prstr(str);
    str = newvstralloc(str,
		       " SERVER_HOST_INSTANCE=\\\"",
		       SERVER_HOST_INSTANCE,
		       "\\\"",
		       NULL);
    prstr(str);
    str = newvstralloc(str,
		       " SERVER_HOST_KEY_FILE=\\\"",
		       SERVER_HOST_KEY_FILE,
		       "\\\"",
		       NULL);
    prstr(str);
    str = newvstralloc(str,
		       " CLIENT_HOST_PRINCIPLE=\\\"",
		       CLIENT_HOST_PRINCIPLE,
		       "\\\"",
		       NULL);
    prstr(str);
    str = newvstralloc(str,
		       " CLIENT_HOST_INSTANCE=\\\"",
		       CLIENT_HOST_INSTANCE,
		       "\\\"",
		       NULL);
    prstr(str);
    str = newvstralloc(str,
		       " CLIENT_HOST_KEY_FILE=\\\"",
		       CLIENT_HOST_KEY_FILE,
		       "\\\"",
		       NULL);
    prstr(str);
    ap_snprintf(lifetime_str, (sizeof(lifetime_str), "%d", TICKET_LIFETIME);
    str = newvstralloc(str, " TICKET_LIFETIME=", lifetime_str, NULL);
    prstr(str);
#endif
#ifdef CLIENT_LOGIN
    str = newvstralloc(str, " CLIENT_LOGIN=\\\"", CLIENT_LOGIN, "\\\"", NULL);
    prstr(str);
#endif
#ifdef FORCE_USERID
    prstr(" FORCE_USERID");
#endif
#ifdef USE_VERSION_SUFFIXES
    prstr(" USE_VERSION_SUFFIXES");
#endif
#ifdef HAVE_GZIP
    prstr(" HAVE_GZIP");
#endif
#ifdef COMPRESS_SUFFIX
    str = newvstralloc(str, " COMPRESS_SUFFIX=\\\"", COMPRESS_SUFFIX, "\\\"",
		       NULL);
    prstr(str);
#endif
#ifdef COMPRESS_FAST_OPT
    str = newvstralloc(str,
		       " COMPRESS_FAST_OPT=\\\"",
		       COMPRESS_FAST_OPT,
		       "\\\"",
		       NULL);
    prstr(str);
#endif
#ifdef COMPRESS_BEST_OPT
    str = newvstralloc(str,
		       " COMPRESS_BEST_OPT=\\\"",
		       COMPRESS_BEST_OPT,
		       "\\\"",
		       NULL);
    prstr(str);
#endif
#ifdef UNCOMPRESS_OPT
    str = newvstralloc(str, " UNCOMPRESS_OPT=\\\"", UNCOMPRESS_OPT, "\\\"",
		       NULL);
    prstr(str);
#endif

    newline();

    printf("  0\n};\n");
    return 0;
}
