/*
 * Amanda, The Advanced Maryland Automatic Network Disk Archiver
 * Copyright (c) 1991-1999 University of Maryland at College Park
 * All Rights Reserved.
 *
 * Permission to use, copy, modify, distribute, and sell this software and its
 * documentation for any purpose is hereby granted without fee, provided that
 * the above copyright notice appear in all copies and that both that
 * copyright notice and this permission notice appear in supporting
 * documentation, and that the name of U.M. not be used in advertising or
 * publicity pertaining to distribution of the software without specific,
 * written prior permission.  U.M. makes no representations about the
 * suitability of this software for any purpose.  It is provided "as is"
 * without express or implied warranty.
 *
 * U.M. DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, INCLUDING ALL
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT SHALL U.M.
 * BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
 * OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 *
 * Authors: the Amanda Development Team.  Its members are listed in a
 * file named AUTHORS, in the root directory of this distribution.
 */
/*
 * $Id: genversion.c,v 1.24 1999/05/25 07:00:50 oliva Exp $
 *
 * dump the current Amanda version info
 */
#include "amanda.h"
#include "version.h"
#include "genversion.h"

#define	LMARGIN		6
#define RMARGIN 	70

static int linelen;

#define	startline(title)	printf("  \"%-*s", LMARGIN, title); linelen = 0
#define	endline()		printf("\\n\",\n")

static void prstr P((const char *));
static void prvar P((const char *, const char *));
int main P((void));

/* Print a string */
static void
prstr(string)
    const char *string;
{
    size_t len = strlen(string) + 1;

    /*
     * If this string overflows this line, and there's other stuff
     * on the line, create a new one.
     */
    if (linelen > 0 && linelen + len >= RMARGIN - LMARGIN) {
	endline();
	startline("");
    }
    printf(" %s", string);
    linelen += len;
}

/* Print a variable */
static void
prvar(var, val)
    const char *var, *val;
{
    static char buf[256];

    snprintf(buf, sizeof(buf), "%s=\\\"%s\\\"", var, val);
    prstr(buf);
}

int
main()
{
    char verstr[STR_SIZE];

    printf("/* version.c - generated by genversion.c - DO NOT EDIT! */\n");
    printf("const char * const version_info[] = {\n");

    startline("build:");
    snprintf(verstr, sizeof(verstr), "Amanda-%s", version());
    prvar("VERSION", verstr);

#ifdef BUILT_DATE
    prvar("BUILT_DATE", BUILT_DATE);
#endif

#ifdef BUILT_MACH
    prvar("BUILT_MACH", BUILT_MACH);
#endif

#ifdef CC
    prvar("CC", CC);
#endif

    endline();

    startline("paths:");

    prvar("bindir", bindir);
    prvar("sbindir", sbindir);
    prvar("libexecdir", libexecdir);
    prvar("mandir", mandir);
    prvar("CONFIG_DIR", CONFIG_DIR);

#ifdef DEV_PREFIX
    prvar("DEV_PREFIX", DEV_PREFIX);
#endif

#ifdef RDEV_PREFIX
    prvar("RDEV_PREFIX", RDEV_PREFIX);
#endif

#ifdef DUMP
    prvar("DUMP", DUMP);
#endif

#ifdef RESTORE
    prvar("RESTORE", RESTORE);
#endif

#ifdef VDUMP
    prvar("VDUMP", VDUMP);
#endif

#ifdef VRESTORE
    prvar("VRESTORE", VRESTORE);
#endif

#ifdef XFSDUMP
    prvar("XFSDUMP", XFSDUMP);
#endif

#ifdef XFSRESTORE
    prvar("XFSRESTORE", XFSRESTORE);
#endif

#ifdef VXDUMP
    prvar("VXDUMP", VXDUMP);
#endif

#ifdef VXRESTORE
    prvar("VXRESTORE", VXRESTORE);
#endif

#ifdef SAMBA_CLIENT
    prvar("SAMBA_CLIENT", SAMBA_CLIENT);
#endif

#ifdef GNUTAR
    prvar("GNUTAR", GNUTAR);
#endif

#ifdef COMPRESS_PATH
    prvar("COMPRESS_PATH", COMPRESS_PATH);
#endif

#ifdef UNCOMPRESS_PATH
    prvar("UNCOMPRESS_PATH", UNCOMPRESS_PATH);
#endif

    prvar("MAILER", MAILER);

#ifdef GNUTAR_LISTED_INCREMENTAL_DIR
    prvar("listed_incr_dir", GNUTAR_LISTED_INCREMENTAL_DIR);
#endif
    endline();

    startline("defs:");

    prvar("DEFAULT_SERVER", DEFAULT_SERVER);
    prvar("DEFAULT_CONFIG", DEFAULT_CONFIG);
    prvar("DEFAULT_TAPE_SERVER", DEFAULT_TAPE_SERVER);
    prvar("DEFAULT_TAPE_DEVICE", DEFAULT_TAPE_DEVICE);

#ifdef AIX_BACKUP
    prstr("AIX_BACKUP");
#endif

#ifdef AIX_TAPEIO
    prstr("AIX_TAPEIO");
#endif

#ifdef BROKEN_VOID
    prstr("BROKEN_VOID");
#endif

#ifdef DUMP_RETURNS_1
    prstr("DUMP_RETURNS_1");
#endif

#ifdef HAVE_MMAP
    prstr("HAVE_MMAP");
#endif

#ifndef HAVE_STRERROR
    prstr("NEED_STRERROR");
#endif

#ifndef HAVE_STRSTR
    prstr("NEED_STRSTR");
#endif

#ifdef HAVE_SYSVSHM
    prstr("HAVE_SYSVSHM");
#endif

#ifdef USE_POSIX_FCNTL
    prstr("LOCKING=POSIX_FCNTL");
#endif
#ifdef USE_FLOCK
    prstr("LOCKING=FLOCK");
#endif
#ifdef USE_LOCKF
    prstr("LOCKING=LOCKF");
#endif
#ifdef USE_LNLOCK
    prstr("LOCKING=LNLOCK");
#endif
#if !defined(USE_POSIX_FCNTL) && !defined(USE_FLOCK) && !defined(USE_LOCK) && !defined(USE_LNLOCK)
    prstr("LOCKING=**NONE**");
#endif

#ifdef STATFS_BSD
    prstr("STATFS_BSD");
#endif

#ifdef STATFS_OSF1
    prstr("STATFS_OSF1");
#endif

#ifdef STATFS_ULTRIX
    prstr("STATFS_ULTRIX");
#endif

#ifdef SETPGRP_VOID
    prstr("SETPGRP_VOID");
#endif

#ifdef ASSERTIONS
    prstr("ASSERTIONS");
#endif

#ifdef DEBUG_CODE
    prstr("DEBUG_CODE");
#endif

#ifdef DEBUG_FILE_WITH_PID
    prstr("DEBUG_FILE_WITH_PID");
#endif

#ifdef BSD_SECURITY
    prstr("BSD_SECURITY");
#endif

#ifdef KRB4_SECURITY
    prstr("KRB4_SECURITY");
#endif

#ifdef KRB5_SECURITY
    prstr("KRB5_SECURITY");
#endif

#ifdef RSH_SECURITY
    prstr("RSH_SECURITY");
#endif

#ifdef USE_AMANDAHOSTS
    prstr("USE_AMANDAHOSTS");
#endif

#ifdef USE_RUNDUMP
    prstr("USE_RUNDUMP");
#endif

#ifdef CLIENT_LOGIN
    prvar("CLIENT_LOGIN", CLIENT_LOGIN);
#endif

#ifdef FORCE_USERID
    prstr("FORCE_USERID");
#endif

#ifdef USE_VERSION_SUFFIXES
    prstr("USE_VERSION_SUFFIXES");
#endif

#ifdef HAVE_GZIP
    prstr("HAVE_GZIP");
#endif

#ifdef COMPRESS_SUFFIX
    prvar("COMPRESS_SUFFIX", COMPRESS_SUFFIX);
#endif

#ifdef COMPRESS_FAST_OPT
    prvar("COMPRESS_FAST_OPT", COMPRESS_FAST_OPT);
#endif

#ifdef COMPRESS_BEST_OPT
    prvar("COMPRESS_BEST_OPT", COMPRESS_BEST_OPT);
#endif

#ifdef UNCOMPRESS_OPT
    prvar("UNCOMPRESS_OPT", UNCOMPRESS_OPT);
#endif

    endline();

    printf("  0\n};\n");

    exit(0);
}
