/* version.c - generated by genversion.c - DO NOT EDIT! */
char *version_info[] = {
  "build: VERSION=\"Amanda-2.3.0.4\"\n",
  "       BUILT_DATE=\"Tue Mar 11 21:03:10 PST 1997\"\n",
  "       BUILT_MACH=\"SunOS earth 5.5.1 Generic sun4u sparc SUNW,Ultra-2\"\n",
  "       CC=\"gcc\"\n",
  "paths: DEV_PREFIX=\"/dev/dsk/\" RDEV_PREFIX=\"/dev/rdsk/\"\n",
  "       DUMP=\"/usr/sbin/ufsdump\" RESTORE=\"/usr/sbin/ufsrestore\"\n",
  "       GNUTAR=\"/opt/amanda/libexec/gtar\"\n",
  "       COMPRESS_PATH=\"/opt/amanda/libexec/gzip\"\n",
  "       UNCOMPRESS_PATH=\"/opt/amanda/libexec/gzip\"\n",
  "       RSH_COMMAND=\"/bin/remsh\" MAILER=\"/usr/bin/mailx\"\n",
  "       bindir=\"/opt/amanda/bin\" libexecdir=\"/opt/amanda/libexec\"\n",
  "       CONFIG_DIR=\"/opt/amanda/config\" mandir=\"/opt/amanda/man\"\n",
  "defs:  DEFAULT_SERVER=\"earth\" DEFAULT_CONFIG=\"DailySet1\"\n",
  "       DEFAULT_TAPE_SERVER=\"earth\"\n",
  "       DEFAULT_TAPE_DEVICE=\"/dev/null\" HAVE_MMAP HAVE_SYSVSHM\n",
  "       NEED_POSIX_FLOCK SETPGRP_VOID ASSERTIONS DEBUG_CODE\n",
  "       BSD_SECURITY CLIENT_LOGIN=\"amanda\" FORCE_USERID HAVE_GZIP\n",
  "       COMPRESS_SUFFIX=\".gz\" COMPRESS_FAST_OPT=\"--fast\"\n",
  "       COMPRESS_BEST_OPT=\"--best\" UNCOMPRESS_OPT=\"-dc\"\n",
  0
};
